### ISSUE TITLE
Implement Pow for Complex

### ISSUE THREAD

**Issue by clarfon** [rust-num/num-complex#18]
See rust-num/num-traits#38 for details on this trait.

**Comment by shingtaklam1324** [comment]
There is the issue of raising a `Complex<T>` to a power of `Complex<T>`, as it you use 

```
a^(b+ic) = a^b[cos(c ln a) + i sin (c ln a)]
```

If `a` is a complex number, then `ln a`has multiple answers, and there is not one definite answer.

**Comment by clarcharr** [comment]
@shingtaklam1324 right, but returning the principal solution is usually what people want. It's like how `asin(1)/π` is really `(8n + 1)/4` but any practical implementation will return `1/4` as you can get any other solution by adding `2n`.

Complex numbers work similarly; solutions can be obtained by repeatedly multiplying a constant complex number, which I don't recall the equation for off the top of my head. The point is that the principal solution is 99% of the time what you want.

I mean, *in theory* you could return an iterator over the solutions because they're countable, but I don't know if that's appropriate outside of niche cases.

**Comment by cuviper** [comment]
FWIW, we do already have [`powc`](https://github.com/rust-num/num-complex/blob/1eaae98cdd0bd1503845471b2dc945a434a01a54/src/lib.rs#L207), and https://github.com/rust-num/num/pull/137#issuecomment-210582027 referenced [this derivation](https://web.archive.org/web/20170104160540/http://www.abecedarical.com/zenosamples/zs_complexnumbers.html).

**Comment by benruijl** [comment]
`powi` would be very welcome! I get some rounding errors when using `powf`:
```
        println!(
            "test: {:?}",
            Complex::new(0., -2. * f64::PI()).powf(1.)
        );
```

Yields: ` Complex { re: 0.00000000000000038473413874435795, im: -6.283185307179586 }`
