### ISSUE TITLE
i128 no_std

### ISSUE THREAD

**Issue by zendurix** [rust-num/num-complex#83]
README says that this crate supports no_std, however it depends on `num-traits` with `i128` feature  (even when run with no default features).
When I test some program that is dependand on num complex, with no-std-check (https://github.com/mystor/cargo-no-std-check)
I get this error: `thread 'main' panicked at 'i128 support was not detected!`

**Comment by cuviper** [comment]
I haven't seen `cargo-no-std-check` before, but it looks like it's using `RUSTC_WRAPPER` to intercept and rewrite target arguments. The `autocfg` crate will need to support this as well, otherwise feature detection is going to be broken in this use case. But in normal use, I expect it's still be fine.

There shouldn't be any real problem with `i128` on `no_std` targets though. I have thought about relaxing those checks such that if the feature is requested, it will go ahead and be used without bothering to probe with `autocfg`.

**Comment by cuviper** [comment]
This should be fixed by `num-traits 0.2.13` via rust-num/num-traits#185.
For the broader problem of `RUSTC_WRAPPER`, I'll leave that to cuviper/autocfg#26.
