### ISSUE TITLE
num_complex users should be allowed to write   let mut x = (1.0, 2,0)_c64 

### ISSUE THREAD

**Issue by pwplus7** [rust-num/num-complex#88]
...

**Comment by cuviper** [comment]
It sounds like you want something like [C++ user-defined literals](https://en.cppreference.com/w/cpp/language/user_literal), but there's no such mechanism in Rust.

**Comment by pwplus7** [comment]
?? let x= 5.4_f64; is a legit Rust stmt and not a C++ statement
.. what I'm suggesting is that crate num_complex should expand this
statement to include complex number literals  represented by real and imag
values

**Comment by cuviper** [comment]
Rust's `f64` is a primitive language-defined type, with built-in support for parsing with the `_f64` suffix. `Complex` is an external type that the Rust compiler knows nothing about when it is parsing your code.

I mentioned C++ only for comparison, because that feature does allow C++ users to define new suffixes like `_c64`. Rust does not have a feature like that, so I can't define any custom suffixes for `num-complex`.

We could possibly create shorter constructors, `c64(1.0, 2.0)`, as discussed in #21, but you would have to `use num_complex::c64;` first to import that function into scope.

**Comment by pwplus7** [comment]
shorter constructors like c64(1.0, 2.0) would help a bunch..The `use` stmt
is no major obstacle
